Debugger: Fix gcc warning
```
error: declaration of ‘using Result = class amber::Result’ [-fpermissive] ... changes meaning of ‘Result’ from ‘class amber::Result’ [-fpermissive]
```

This type alias is now actually not required, as the anonymous namespace was moved into the amber::vulkan namespace as part of an earlier review comment. Just remove it.