Add missing cache path for Vulkan header when using CMake FindVulkan
This fixes compilation errors of "fatal error: 'vulkan/vulkan.h' file
not found" when using CMake 3.7's FindVulkan.