include missing <cstdint>
gcc-13 exposed errors like below due to it removing indirect includes of
these headers in libstdc++ [1]

../git/external/amber/src/include/amber/shader_info.h:60:15: error: 'uint32_t' was not declared in this scope
   60 |   std::vector<uint32_t> shader_data;
      |               ^~~~~~~~

[1] https://www.gnu.org/software/gcc/gcc-13/porting_to.html

Signed-off-by: Khem Raj <raj.khem@gmail.com>