Rolling 10 dependencies (#756)
Roll third_party/clspv/ 01bb48007..b60b1fcd0 (8 commits)

https://github.com/google/clspv/compare/01bb48007d0a...b60b1fcd0abb

$ git log 01bb48007..b60b1fcd0 --date=short --no-merges --format='%ad %ae %s'
2019-12-13 alanbaker Allow the work_group_barrier alias for barrier (#467)
2019-12-12 alanbaker Unsampled image reads (#465)
2019-12-10 alanbaker Update to amber optional dep syncing (#463)
2019-12-10 alanbaker Add Amber bot functionality (#461)
2019-12-10 alanbaker Deprecate the sampler map (#453)
2019-12-10 alanbaker Support 1D images (#459)
2019-12-10 alanbaker Dummy scripts for amber bot (#460)
2019-12-09 kpet Support sampled read_image{f,i,ui} with integer coordinates for 2D/3D images (#457)

Roll third_party/clspv-llvm/ 6626e5a06..079ef783d (573 commits)

https://github.com/llvm/llvm-project/compare/6626e5a06a99...079ef783dd55

$ git log 6626e5a06..079ef783d --date=short --no-merges --format='%ad %ae %s'
2019-12-16 gribozavr Revert "[clangd] Implement "textDocument/documentLink" protocol support"
2019-12-16 gchatelet Revert "[Alignment][NFC] Deprecate CreateMemCpy/CreateMemMove"
2019-12-16 thakis gn build: (manually, belatedly) merge r358832
2019-12-16 thakis gn build: (manually, belatedly) merge r371898
2019-12-16 david.tellenbach Reland [AArch64][MachineOutliner] Return address signing for outlined functions
2019-12-16 kristof.beyls find_interesting_reviews.py: adapt to github monorepo
2019-12-16 pavel [lldb] Use file-based synchronization in TestVSCode_attach
2019-12-13 gchatelet [llvm-exegesis] Set up AsmTargetStreamer in readSnippets
2019-12-13 gchatelet [Alignment][NFC] Deprecate CreateMemCpy/CreateMemMove
2019-12-16 andrzej.warzynski [AArch64][SVE2] Add intrinsics for binary narrowing operations
2019-12-16 kristof.beyls [AArch64] Enable emission of stack maps for non-Mach-O binaries on AArch64.
2019-12-16 andrzej.warzynski [Aarch64][SVE] Add intrinsics for scatter stores
2019-12-16 teemperor [lldb] Add unit test for ClangASTImporter
2019-12-13 Alexander.Richardson Add initial tests for update_{llc_,cc_,}test_checks.py
2019-12-16 teemperor [lldb][NFC] Remove all overloads of Copy/DeportType in ClangASTImporter
2019-12-10 pavel [lldb] Centralize desugaring of decltype-like types in ClangASTContext
2019-12-16 jay.foad Fix whitespace.
2019-12-13 bjorn.a.pettersson [BasicBlockUtils] Fix dbg.value elimination problem in MergeBlockIntoPredecessor
2019-12-13 bjorn.a.pettersson [LoopRotate] Add test case to show dbg value problem
2019-12-12 bjorn.a.pettersson [BasicBlockUtils] Add utility to remove redundant dbg.value instrs
2019-12-16 jay.foad Fix for AMDGPU MUL_I24 known bits calculation
2019-12-16 kbobyrev [NFC] Fix typos in Clangd and Clang
2019-12-16 teemperor [lldb][NFC] Move definition of ClangASTMetadata out of ClangExternalASTSourceCommon.h
2019-12-14 v.churavy [CodegenPrepare] Guard against degenerate branches
2019-12-16 sjoerd.meijer [ARM] Move MVE opcode helper functions to ARMBaseInstrInfo. NFC.
2019-12-16 teemperor [lldb][NFC] Fix file header of TestClangASTContext.cpp
2019-12-16 kadircet [clangd] Get rid of raw string literals in macro calls
2019-12-16 teemperor [lldb][NFC] Remove ClangASTImporter::ResolveDeclOrigin
2019-12-13 gribozavr Fix title underline in LangRef
2019-12-16 teemperor [lldb][NFC] Remove unnecessary includes in source/Commands
2019-12-16 teemperor [lldb][NFC] Replace ClangASTImporter's use of map/set with SmallPtrSet and DenseMap
2019-12-15 richard Mark the major papers for C++20 consistent comparisons as "done", and start publishing the corresponding feature-test macro.
2019-12-13 richard [c++20] Compute exception specifications for defaulted comparisons.
2019-12-13 richard Properly compute whether statement expressions can throw, rather than conservatively assuming they always can.
2019-12-13 richard Resolve exception specifications after marking the corresponding function as referenced, not before.
2019-12-15 maskray [ELF] Delete redundant isLive() check. NFC
2019-12-15 lhames [examples] Rename LLJITWithJITLink to LLJITWithCustomObjectLinkingLayer.
2019-12-15 lhames [Orc][LLJIT] Automatically use JITLink for LLJIT on supported platforms.
2019-12-15 lhames [examples] Update LLJITWithJITLink example for change in c0143f37dab.
2019-12-04 maskray [llvm-objcopy][ELF] -O binary: use LMA instead of sh_offset to decide where to write section contents
2019-12-16 nuta [llvm-objcopy][MachO] Implement --add-section
2019-12-15 maskray [MC] Delete STT_SECTION special cases from MCSymbolELF::setType and setBinding
2019-12-16 tclin914 [PowerPC] Fix %llvm.ppc.altivec.vc* lowering
2019-12-15 lhames [ORC] Make ObjectLinkingLayer own its jitlink::MemoryManager.
2019-12-15 maskray [MC] Assume CommentStream is non-null in MCDisassembler::tryAdding*
2019-12-15 maskray [MC] Ignore VK_WEAKREF in MCValue::getAccessVariant
2019-12-15 maskray [MC] Delete unused MCAsmInfoELF::UsesNonexecutableStackSection after EM_WEBASSEMBLY was removed in D48744
2019-12-15 lhames [Kaleidoscope][BuildingAJIT] Add a missing std::move.
2019-12-15 risemann [lldb] Remove RTTI in ClangExternalASTSourceCommon based on a global map of known instances
2019-12-15 koraq [AST] Use a reference in a range-based for
(...)
2019-12-10 qshanz [NFC][MacroFusion] Adding the assertion if someone want to fuse more than 2 instructions
2019-12-09 echristo Remove unused Unit test directory for xray.
2019-12-05 richard [c++20] Fix handling of unqualified lookups from a defaulted comparison function.
2019-12-09 huihuiz [NFC] Add { } to silence compiler warning [-Wmissing-braces].
2019-12-09 jonas [llvm/dwarfdump] Use the architecture string to filter.
2019-12-09 ditaliano [FormatManager] GetCandidateLanguages shouldn't know about ValueObject.
2019-12-10 chen3.liu add support for strict operation fpextend/fpround/fsqrt on X86 backend
2019-12-09 echristo Revert "[ARM][MVE] Add intrinsics for immediate shifts." and two follow-on commits: one warning fix and one functionality.
2019-12-09 rnk Avoid Attr.h includes, CodeGen edition
2019-12-06 efriedma [ConstantFold][SVE] Fix constant folding for shufflevector.
2019-12-09 david.bolvansky [Codegen][X86] Modernize/regenerate old tests. NFCI.
2019-12-06 efriedma [AArch64][SVE] Implement SPLAT_VECTOR for i1 vectors.
2019-12-05 richard [c++20] Defaulted comparison support for array members.
2019-12-09 ditaliano [FormatManager] Provide a single entrypoint for GetCandidateLanguages().
2019-12-09 phabouzit Also synthesize _cmd and self for properties
2019-12-09 csigg Implement LWG#1203 for raw_ostream.
2019-12-06 eugenis [hwasan] Offline symbolization script.
2019-12-09 jji [PowerPC] [NFC] Cleanup xxpermdi peephole optimization
2019-12-05 sivachandra [libc] Add implementation of errno and define the other macros of errno.h.
2019-11-01 johannes [IPConstantProp][NFCI] Improve and modernize tests
2019-12-08 johannes [ValueTracking] Allow context-sensitive nullness check for non-pointers
2019-12-09 rnk Include Stmt.h where it seems to be necessary for modules builds
2019-12-05 yamauchi [PGO][PGSO] Instrument the code gen / target passes.
2019-12-09 craig.topper [Attr] Move ParsedTargetAttr out of the TargetAttr class
2019-12-09 richard [c++20] Fix incorrect assumptions in checks for comparison category types.
2019-11-26 puyan [clang][IFS] Allow 2 output files when using -o and -c with clang IFS stubs.
2019-12-09 maskray Fix clang -Wcovered-switch-default after llvmorg-10-init-11484-g6626e5a06a9
2019-12-09 spatel [InstCombine] add tests for shuffle with insertelement operand; NFC
2019-12-05 jji [PowerPC][NFC] Rename ANDI(S)o8 to ANDI(S)8o
2019-12-07 serhiy.redko The field ‘totalFrames’ which is total number of frames available, is mandatory in StackTraces response for VSCode extension that implements DAP and declares capability 'supportsDelayedStackTraceLoading':
2019-12-09 sam.mccall [clangd] also filter out another possible diag from MS ASM syntax
2019-12-09 tibor.brunner Magic number checker shouldn't warn on user defined string literals
2019-12-05 peter scudo: Add a basic malloc/free benchmark.
2019-12-06 peter Reland 198fbcb8, "Driver: Don't look for libc++ headers in the install directory on Android.", which was reverted in b3249027.
2019-12-09 pavel [lldb] Clean up accidentally passing TestDeadStrip.py
2019-12-09 kadircet [clangd] Delete ctor initializers while moving functions out-of-line
2019-12-09 kadircet [clangd] Delete default arguments while moving functions out-of-line
2019-12-06 mark.murray [ARM][MVE][Intrinsics] Add VQADDQ, VHADDQ, VRHADDQ, VQSUBQ, VHSUBQ, VQDMULHQ, VQRDMULHQ intrinsics.
2019-12-04 mark.murray [ARM][MVE][Intrinsics] Add VMULL[BT]Q_(INT|POLY) intrinsics.
2019-12-09 sd.fertile [PowerPC] Refactor FinishCall. [NFC]
2019-12-09 jonas [lldb/SWIG] Guard Python type map in SWIG interface by SWIGPYTHON
2019-12-09 tatyana [lldb][CMake] Fix build for the case of custom libedit installation
2019-12-09 simon.tatham [ARM] Fix NEON failure introduced by D71065.
2019-12-09 31459023+hctim [GWP-ASan] 32-bit test pointers, allow multi-init for test.
2019-12-09 hokein.wu Fix the compiler warnings: "-Winconsistent-missing-override", "-Wunused-variable"
2019-12-09 hokein.wu [clangd] Implement range patching heuristics for cross-file rename.
2019-12-06 francesco.petrogalli [llvm][VFABI] Add more testing for LLVM internal mangling.
2019-12-09 simon.tatham [ARM][MVE] Add intrinsics for immediate shifts.
2019-12-09 thomasraoux [ModuloSchedule] Fix data types in ModuloScheduleExpander::isLoopCarried
2019-12-09 hokein.wu [clangd] Use expansion location when the ref is inside macros.

Roll third_party/dxc/ b0731e7f2..274945808 (1 commit)

https://github.com/Microsoft/DirectXShaderCompiler/compare/b0731e7f2d45...2749458081b6

$ git log b0731e7f2..274945808 --date=short --no-merges --format='%ad %ae %s'
2019-12-10 jaebaek [spirv] fix crash from debug info gen with opt (#2619)

Roll third_party/glslang/ ff61c18f1..ebf634bca (3 commits)

https://github.com/KhronosGroup/glslang/compare/ff61c18f1bbc...ebf634bcaa3e

$ git log ff61c18f1..ebf634bca --date=short --no-merges --format='%ad %ae %s'
2019-12-12 greg Update spriv-tools known good
2019-12-09 cepheus Fix #2020: PR #1977 broke HLSL member consistency, this finishes it...
2019-12-09 cepheus Fix: #2014: Don't do "extension-on && version >= ..." keyword checks.

Roll third_party/googletest/ 78fdd6c00..5b162a79d (7 commits)

https://github.com/google/googletest/compare/78fdd6c00b8f...5b162a79d49d

$ git log 78fdd6c00..5b162a79d --date=short --no-merges --format='%ad %ae %s'
2019-12-12 absl-team Googletest export
2019-12-11 absl-team Googletest export
2019-12-10 absl-team Googletest export
2019-12-06 misterg Googletest export
2019-11-17 krystian.kuzniarek remove MSVC workaround: warning 4355
2019-11-14 krystian.kuzniarek remove MSVC workaround: error C2665
2019-11-22 krystian.kuzniarek remove g++ 2.95.0 workaround: no space after first comma in macros

Roll third_party/shaderc/ eec373d9e..979ad21e8 (4 commits)

https://github.com/google/shaderc/compare/eec373d9e7a4...979ad21e8422

$ git log eec373d9e..979ad21e8 --date=short --no-merges --format='%ad %ae %s'
2019-12-12 rharrison Implement a C++ only version for ForEachCombinedImageSamplers (#936)
2019-12-11 9856269+sarahM0 Add missing APIs for GLSL in Dawn (#934)
2019-12-11 dneto Don't assume locations of spirv-tools, effcee, and RE2 are located (#931)
2019-12-10 rharrison Rolling 5 dependencies (#933)

Roll third_party/spirv-tools/ 983b5b4fc..96354f504 (6 commits)

https://github.com/KhronosGroup/SPIRV-Tools/compare/983b5b4fccea...96354f5047bf

$ git log 983b5b4fc..96354f504 --date=short --no-merges --format='%ad %ae %s'
2019-12-12 afdx spirv-fuzz: Fuzzer pass to merge blocks (#3097)
2019-12-11 stevenperron Start SPIRV-Tools v2020.1
2019-12-11 stevenperron Finalize SPIRV-Tools v2019.5
2019-12-11 stevenperron Update CHANGES
2019-12-10 stevenperron Don't crash when folding construct of empty struct (#3092)
2019-12-10 afdx spirv-fuzz: function outlining fuzzer pass (#3078)

Roll third_party/swiftshader/ 84d0f7cbb..fbbfeb700 (42 commits)

https://swiftshader.googlesource.com/SwiftShader.git/+log/84d0f7cbbb9b..fbbfeb700295

$ git log 84d0f7cbb..fbbfeb700 --date=short --no-merges --format='%ad %ae %s'
2019-12-13 chrisforbes Add missing source file to android build
2019-12-13 swiftshader.regress Regres: Update test lists @ ebb0bec9
2019-12-12 sergeyu Use allocateExecutable() in LLVMReactor
2019-12-12 sugoi Fix BCn related SwANGLE test failure
2019-12-12 capn Prevent clang-format from splitting shift operator
2019-12-11 sugoi Support for BC1, BC2, BC3, BC4 and BC5
2019-12-10 bclayton src/Vulkan/Debug: Add scope for case block
2019-12-02 bclayton Vulkan/Debug: Add Server
2019-12-02 bclayton Vulkan/Debug: Add Context
2019-12-11 bclayton Tweaks to make clang-format produce better code
2019-12-11 amaiorano Add EmulatedReactor.cpp to Subzero.vcxproj
2019-12-10 bclayton Regres: Fix debug macro detection
2019-12-10 capn Do not indent C++ namespace contents
2019-12-03 bclayton Vulkan: Add description methods to all commands.
2019-12-03 bclayton .vscode: Add cppdap to includePath
2019-12-11 swiftshader.regress Regres: Update test lists @ 544ae91e
2019-12-10 capn Enable vk-unittests with Subzero JIT
2019-12-10 bclayton Kokoro: Split tests into Debug and RelWithDebInfo
2019-12-10 chrisforbes Accept ImageCubeArray SPIRV capability
2019-12-02 bclayton Vulkan/Debug: Add Thread and EventListener
2019-12-02 bclayton Vulkan/Debug: Add Location
2019-12-02 bclayton Vulkan/Debug: Add File
2019-12-02 bclayton Vulkan/Debug: Add WeakMap
2019-12-02 bclayton Vulkan/Debug: Add Value and Variable
2019-12-02 bclayton Vulkan/Debug: Add Type
2019-12-10 bclayton CMakeLists: Fix logic of BUILD_CPPDAP
2019-12-10 swiftshader.regress Regres: Update test lists @ d00dfe49
2019-12-10 chrisforbes Advertise VK_PRESENT_MODE_MAILBOX_KHR
2019-12-10 bclayton Regres: Reduce scope of regres CI emails
2019-12-10 amaiorano Fix REACTOR_DEFAULT_OPT_LEVEL not actually applying
2019-12-10 capn Remove Visual Studio Vulkan project files
2019-12-02 bclayton Vulkan/Debug: Add ID
2019-12-09 chrisforbes Remove Float->UInt conversion workaround
2019-12-09 capn Add Float to UInt unit test
2019-12-09 amaiorano Add REACTOR_DEFAULT_OPT_LEVEL macro
2019-12-04 amaiorano Subzero: fix alloca return address allocation
2019-12-06 amaiorano Subzero: proper fix for assert(Dest->hasReg())
2019-12-02 bclayton CMakeLists: Add CMake rules for Vulkan debugger
2019-11-08 bclayton Add github.com/google/cppdap as a third_party dependency
2019-11-18 bclayton Add github.com/nlohmann/json as a third_party dependency
2019-12-09 capn Enforce int and short to be 32- and 16-bit respectively
2019-12-02 sugoi Cubemap array support

Roll third_party/vulkan-loader/ 6ec1838ba..206979855 (4 commits)

https://github.com/KhronosGroup/Vulkan-Loader/compare/6ec1838ba00f...2069798558ec

$ git log 6ec1838ba..206979855 --date=short --no-merges --format='%ad %ae %s'
2019-12-12 lenny loader: Add custom terminator to tool properties
2019-12-10 caio.oliveira build: Fix Vulkan registry detection
2019-12-11 lenny codegen: Fix crash in tooling info terminator
2019-12-09 mark build: Update for 1.1.130 header version

Roll third_party/vulkan-validationlayers/ f34b9fb08..2b19f3916 (27 commits)

https://github.com/KhronosGroup/Vulkan-ValidationLayers/compare/f34b9fb086b3...2b19f3916726

$ git log f34b9fb08..2b19f3916 --date=short --no-merges --format='%ad %ae %s'
2019-12-12 mark tests: Add tests for DescTemplates fixes and new VUIDs
2019-12-12 mark objlifetimes: Fix CreateDescUpdateTemplates object val
2019-12-13 mark build: Update glslang & VulkanTools known-good IDs
2019-11-29 geecandrey corechecks: Invalid error message in vkCmdPipelineBarrier
2019-12-10 mark tests: Add positive test for tooling ext query
2019-12-10 mark chassis: Support tooling queries in khronos layer
2019-12-10 mark chassis: Add physicaldevice support for tools info API
2019-12-10 mark stateless: Update for new struct_type_array case
2019-12-10 mark chassis: Implement GetPhysicalDeviceProcAddr layer func
2019-12-09 jeremyk layers: Fix issue 1416
2019-12-12 jzulauf layers: Improve const shared pointer handling
2019-12-12 mark corechecks: Correct swapchain validation error text
2019-12-10 tony gpu: Add validation for VK_KHR_buffer_device_address
2019-12-10 jbolz tests: Add tests for VK_KHR_buffer_device_address
2019-12-10 jbolz layers: Add VK_KHR_buffer_device_address support
2019-12-04 tobias.hector tests: Added tests for new vkAllocateMemory validation
2019-11-28 tobias.hector layers: Introduce validation for vkAllocateMemory VUIDs
2019-12-10 jeremy tests: Test overlapping push constant ranges
2019-12-10 jeremy corechecks: Fix overlapping push constant ranges
2019-12-10 mark layers: Remove vuid mapping file
2019-12-09 mark build: Update for 1.1.130 version of Vulkan header
2019-12-10 mark tests: Fix stray VUID ref in buffer_image_memory_sampler
2019-12-09 mark tests: Fix stray VUID refs in positivelayertests
2019-12-09 mark corechecks: Fix incorrect CmdSetViewportWScalingNV names
2019-11-26 tony tests: Add pos test for GetProcAddr with extensions
2019-11-26 tony layers: Fix GetProcAddr for promoted extensions
2019-12-05 shannon build: Update known-good for 1.1.129 Vulkan header

Created with:
  roll-dep third_party/clspv third_party/clspv-llvm third_party/dxc third_party/glslang third_party/googletest third_party/lodepng third_party/shaderc third_party/spirv-headers third_party/spirv-tools third_party/swiftshader third_party/vulkan-headers third_party/vulkan-loader third_party/vulkan-validationlayers